Ability to add second headers in smart table
maestrano/mno-ui-elements pull request #18
Opened 2017-11-01 19:08 UTC by manu-d

For [[APPINT-1044]](https://maestrano.atlassian.net/browse/APPINT-1044)
Add second headers to smart table. Just like the dynamic attributes, I added some custom rendering, so that these new headers can have different html tags.
Here is an example of what it looks like: 
<img width="584" alt="screen shot 2017-11-01 at 19 05 16" src="https://user-images.githubusercontent.com/11267460/32292389-f8165034-bf37-11e7-8e52-e1d3a86c43b0.png">

2017-11-02 14:56 UTC, manu-d commented
@xaun @alexnoox Please, review

2017-11-03 06:02 UTC, alexnoox requested changes

2017-11-03 06:02 UTC, alexnoox commented on src/components/sortable-table/render-dynamic-attr.directive.coffee
> +.directive('mnoRenderDynamicHeader', ($compile)->
Please move this directive in a separate file

2017-11-03 12:28 UTC, xaun approved these changes
Other than what Noox commented - LGTM 👍

2017-11-10 00:36 UTC, alexnoox approved these changes

2017-11-13 22:56 UTC, merged