[MNOE-777] Extra max auto-height for widgets
maestrano/mno-ui-elements pull request #25
Opened 2017-12-04 06:15 UTC by enizor

10 users (larger cells) did not fit in the previous value.

2017-12-04 06:16 UTC, enizor commented
A secon commit will arrive with a centered sortable-table arrow

2017-12-04 06:48 UTC, enizor commented
Using centered icons: 
- Before
![image](https://user-images.githubusercontent.com/25256520/33539475-beb749c2-d91a-11e7-94e0-40b8d92ba378.png) ![image](https://user-images.githubusercontent.com/25256520/33539523-fd2d1f60-d91a-11e7-87d2-e6c5a5dfc16f.png)
- After
 ![image](https://user-images.githubusercontent.com/25256520/33539492-d66d9436-d91a-11e7-8c79-64d0ca580c9e.png)![image](https://user-images.githubusercontent.com/25256520/33539536-0a0cb6be-d91b-11e7-9ac1-9db34a2e4561.png)

2017-12-04 23:30 UTC, alexnoox requested changes

2017-12-04 23:30 UTC, alexnoox commented on src/components/sortable-table/sortable-table.less
>        // Content code for 'fa-sort-asc'
Update comment `// Content code for 'fa-caret-up'`

2017-12-04 23:30 UTC, alexnoox commented on src/components/sortable-table/sortable-table.less
>        // Content code for 'fa-sort-desc'
Update comment `// Content code for 'fa-caret-down'`

2017-12-04 23:33 UTC, alexnoox commented
Please also commit a build as the last commit 😄

2017-12-05 00:15 UTC, alexnoox approved these changes

2017-12-05 00:20 UTC, alexnoox commented
👍

2017-12-05 00:20 UTC, merged